</$objtype/mkfile

P=quad

LIB=lib$P.$O.a
OFILES=$P.$O
HFILES=$P.h

</sys/src/cmd/mklib

CLEANFILES=$O.quadtest

$O.quadtest: quadtest.$O $LIB ../libagar/libagar.$O.a
	$LD $LDFLAGS -o $target $prereq

quadtest.$O: quadtest.c
	$CC $CFLAGS -I../libagar quadtest.c
